service: fantasy-footbal-players-stats-lambda

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.stats
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
