service: fantasy-footbal-players-stats-lambda

provider:
  name: aws
  runtime: nodejs12.x

functions:
  stats:
    handler: handler.stats
    events:
      - http:
          path: /stats/{period}
          method: get
          request:
            parameters:
              paths:
                period: true
              querystrings:
                weekId: false
                monthId: false

plugins:
  - serverless-plugin-typescript
  - serverless-offline
